apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}-configmap
  data:
    nginx-location.conf: |
      location / {
        try_files $uri$args $uri$args/ /index.html;
      }
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: parametrosui
