export interface AbmLocalidades {
    par_modo: string,
    codigo_postal: number,
    sub_codigo_postal: string,
    descripcion:string,
    letra_provincia:string,
    flete_transporte: string,
    posicion_referente: string,
    visitado_auditor: string,
    zona_promocion: string,
    codigo_departamento: string,
    zona_envio: string,
    ingreso_ticket: string,
    zona_atencion: string,
    cant_habitantes: string,
}