apiVersion: v1
kind: Template
metadata:
  name: parametrosui
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
          namespace: openshift
      type: Source
    triggers:
    - type: "ConfigChange" 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          name: parametrosui
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: /opt/app-root/etc/nginx.default.d
            name: ${APP_NAME}-volume
        restartPolicy: Always
        volumes:
        - configMap:
            name: ${APP_NAME}-configmap
          name: ${APP_NAME}-volume
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}-configmap
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: parametrosui
